gui_util: added missing logger
Threw this exception:
marius@krach:/media/usb0$ snuffler --markers=meta/events.pf
Res_all_NKC_taper/* --stations=/media/usb0/meta/stations.pf
Traceback (most recent call last):
  File "/usr/local/bin/snuffler", line 5, in <module>
    snuffler.snuffler_from_commandline()
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/snuffler.py",
line 762, in snuffler_from_commandline
    markers.extend(pyrocko.pile_viewer.Marker.load_markers(marker_fn))
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gui_util.py",
line 555, in load_markers
    logger.warn('Invalid marker definition in line %i of file "%s"' %
(iline+1, fn))
NameError: global name 'logger' is not defined